/*
 * Italian Invoice API
 *
 *  ## Overview  The Invoice API is a RESTful API that allows you to send and receive invoices through the Italian Servizio di Interscambio (Interchange Service).  ### Authentication  The Invoicetronic API uses API keys to authenticate requests. If you don't have any API Key, you can request one by registering with the [Invoicetronic Developer Portal][1].  Test mode secret keys have the prefix `ik_test_` and live mode secret keys have the prefix `ik_live_`. Make sure to use the correct key for each environment.  > Your API keys carry many privileges, so be sure to keep them secure! Do not share your secret API keys in publicly > accessible areas such as GitHub, client-side code, and so forth.  All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.  #### Basic Authentication  Basic Authentication is how you authenticate with the API. Use your API Key as the username and leave the password empty. If your client does not allow empty passwords, you can use any value as the password. Here's an example of how to authenticate with Basic Authentication and curl:  ```curl curl https://api.invoicetronic.com/invoice/v1/send \\     -u ik_test_1234567890abcdefg:  # The colon prevents curl from asking for a password. ```  [1]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: v1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Invoicetronic.InvoiceApi.Client;
using Invoicetronic.InvoiceApi.Api;
// uncomment below to import models
//using Invoicetronic.InvoiceApi.Model;

namespace Invoicetronic.InvoiceApi.Test.Api
{
    /// <summary>
    ///  Class for testing ReceiveApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReceiveApiTests : IDisposable
    {
        private ReceiveApi instance;

        public ReceiveApiTests()
        {
            instance = new ReceiveApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReceiveApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReceiveApi
            //Assert.IsType<ReceiveApi>(instance);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveGet
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? companyId = null;
            //string identifier = null;
            //bool? unread = null;
            //string committente = null;
            //string prestatore = null;
            //string fileName = null;
            //DateTime? lastUpdateFrom = null;
            //DateTime? lastUpdateTo = null;
            //DateTime? dateSentFrom = null;
            //DateTime? dateSentTo = null;
            //DateTime? documentDateFrom = null;
            //DateTime? documentDateTo = null;
            //string documentNumber = null;
            //int? page = null;
            //int? pageSize = null;
            //var response = instance.InvoiceV1ReceiveGet(companyId, identifier, unread, committente, prestatore, fileName, lastUpdateFrom, lastUpdateTo, dateSentFrom, dateSentTo, documentDateFrom, documentDateTo, documentNumber, page, pageSize);
            //Assert.IsType<List<Receive>>(response);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveIdDelete
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.InvoiceV1ReceiveIdDelete(id);
            //Assert.IsType<Receive>(response);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveIdGet
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.InvoiceV1ReceiveIdGet(id);
            //Assert.IsType<Receive>(response);
        }
    }
}
