/*
 * Italian Invoice API
 *
 *  ## Overview  The Invoice API is a RESTful API that allows you to send and receive invoices through the Italian Servizio di Interscambio (Interchange Service).  ### Authentication  The Invoicetronic API uses API keys to authenticate requests. If you don't have any API Key, you can request one by registering with the [Invoicetronic Developer Portal][1].  Test mode secret keys have the prefix `ik_test_` and live mode secret keys have the prefix `ik_live_`. Make sure to use the correct key for each environment.  > Your API keys carry many privileges, so be sure to keep them secure! Do not share your secret API keys in publicly > accessible areas such as GitHub, client-side code, and so forth.  All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.  #### Basic Authentication  Basic Authentication is how you authenticate with the API. Use your API Key as the username and leave the password empty. If your client does not allow empty passwords, you can use any value as the password. Here's an example of how to authenticate with Basic Authentication and curl:  ```curl curl https://api.invoicetronic.com/invoice/v1/send \\     -u ik_test_1234567890abcdefg:  # The colon prevents curl from asking for a password. ```  [1]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: v1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DatiGeneraliDocumento
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatiGeneraliDocumentoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatiGeneraliDocumento
        //private DatiGeneraliDocumento instance;

        public DatiGeneraliDocumentoTests()
        {
            // TODO uncomment below to create an instance of DatiGeneraliDocumento
            //instance = new DatiGeneraliDocumento();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatiGeneraliDocumento
        /// </summary>
        [Fact]
        public void DatiGeneraliDocumentoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatiGeneraliDocumento
            //Assert.IsType<DatiGeneraliDocumento>(instance);
        }

        /// <summary>
        /// Test the property 'TipoDocumento'
        /// </summary>
        [Fact]
        public void TipoDocumentoTest()
        {
            // TODO unit test for the property 'TipoDocumento'
        }

        /// <summary>
        /// Test the property 'Divisa'
        /// </summary>
        [Fact]
        public void DivisaTest()
        {
            // TODO unit test for the property 'Divisa'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Numero'
        /// </summary>
        [Fact]
        public void NumeroTest()
        {
            // TODO unit test for the property 'Numero'
        }

        /// <summary>
        /// Test the property 'DatiRitenuta'
        /// </summary>
        [Fact]
        public void DatiRitenutaTest()
        {
            // TODO unit test for the property 'DatiRitenuta'
        }

        /// <summary>
        /// Test the property 'DatiBollo'
        /// </summary>
        [Fact]
        public void DatiBolloTest()
        {
            // TODO unit test for the property 'DatiBollo'
        }

        /// <summary>
        /// Test the property 'DatiCassaPrevidenziale'
        /// </summary>
        [Fact]
        public void DatiCassaPrevidenzialeTest()
        {
            // TODO unit test for the property 'DatiCassaPrevidenziale'
        }

        /// <summary>
        /// Test the property 'ScontoMaggiorazione'
        /// </summary>
        [Fact]
        public void ScontoMaggiorazioneTest()
        {
            // TODO unit test for the property 'ScontoMaggiorazione'
        }

        /// <summary>
        /// Test the property 'ImportoTotaleDocumento'
        /// </summary>
        [Fact]
        public void ImportoTotaleDocumentoTest()
        {
            // TODO unit test for the property 'ImportoTotaleDocumento'
        }

        /// <summary>
        /// Test the property 'Arrotondamento'
        /// </summary>
        [Fact]
        public void ArrotondamentoTest()
        {
            // TODO unit test for the property 'Arrotondamento'
        }

        /// <summary>
        /// Test the property 'Causale'
        /// </summary>
        [Fact]
        public void CausaleTest()
        {
            // TODO unit test for the property 'Causale'
        }

        /// <summary>
        /// Test the property 'Art73'
        /// </summary>
        [Fact]
        public void Art73Test()
        {
            // TODO unit test for the property 'Art73'
        }
    }
}
