/*
 * Italian Invoice API
 *
 *  ## Overview  The Invoice API is a RESTful API that allows you to send and receive invoices through the Italian Servizio di Interscambio (Interchange Service).  ### Authentication  The Invoicetronic API uses API keys to authenticate requests. If you don't have any API Key, you can request one by registering with the [Invoicetronic Developer Portal][1].  Test mode secret keys have the prefix `ik_test_` and live mode secret keys have the prefix `ik_live_`. Make sure to use the correct key for each environment.  > Your API keys carry many privileges, so be sure to keep them secure! Do not share your secret API keys in publicly > accessible areas such as GitHub, client-side code, and so forth.  All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.  #### Basic Authentication  Basic Authentication is how you authenticate with the API. Use your API Key as the username and leave the password empty. If your client does not allow empty passwords, you can use any value as the password. Here's an example of how to authenticate with Basic Authentication and curl:  ```curl curl https://api.invoicetronic.com/invoice/v1/send \\     -u ik_test_1234567890abcdefg:  # The colon prevents curl from asking for a password. ```  [1]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: v1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Invoicetronic.InvoiceApi.Client.OpenAPIDateConverter;

namespace Invoicetronic.InvoiceApi.Model
{
    /// <summary>
    /// DatiGenerali
    /// </summary>
    [DataContract(Name = "DatiGenerali")]
    public partial class DatiGenerali : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DatiGenerali" /> class.
        /// </summary>
        /// <param name="datiGeneraliDocumento">datiGeneraliDocumento.</param>
        /// <param name="datiOrdineAcquisto">datiOrdineAcquisto.</param>
        /// <param name="datiContratto">datiContratto.</param>
        /// <param name="datiConvenzione">datiConvenzione.</param>
        /// <param name="datiRicezione">datiRicezione.</param>
        /// <param name="datiFattureCollegate">datiFattureCollegate.</param>
        /// <param name="datiSal">datiSal.</param>
        /// <param name="datiDdt">datiDdt.</param>
        /// <param name="datiTrasporto">datiTrasporto.</param>
        /// <param name="fatturaPrincipale">fatturaPrincipale.</param>
        public DatiGenerali(DatiGeneraliDocumento datiGeneraliDocumento = default(DatiGeneraliDocumento), List<DatiOrdineAcquisto> datiOrdineAcquisto = default(List<DatiOrdineAcquisto>), List<DatiContratto> datiContratto = default(List<DatiContratto>), List<DatiConvenzione> datiConvenzione = default(List<DatiConvenzione>), List<DatiRicezione> datiRicezione = default(List<DatiRicezione>), List<DatiFattureCollegate> datiFattureCollegate = default(List<DatiFattureCollegate>), List<DatiSAL> datiSal = default(List<DatiSAL>), List<DatiDDT> datiDdt = default(List<DatiDDT>), DatiTrasporto datiTrasporto = default(DatiTrasporto), FatturaPrincipale fatturaPrincipale = default(FatturaPrincipale))
        {
            this.DatiGeneraliDocumento = datiGeneraliDocumento;
            this.DatiOrdineAcquisto = datiOrdineAcquisto;
            this.DatiContratto = datiContratto;
            this.DatiConvenzione = datiConvenzione;
            this.DatiRicezione = datiRicezione;
            this.DatiFattureCollegate = datiFattureCollegate;
            this.DatiSal = datiSal;
            this.DatiDdt = datiDdt;
            this.DatiTrasporto = datiTrasporto;
            this.FatturaPrincipale = fatturaPrincipale;
        }

        /// <summary>
        /// Gets or Sets DatiGeneraliDocumento
        /// </summary>
        [DataMember(Name = "dati_generali_documento", EmitDefaultValue = false)]
        public DatiGeneraliDocumento DatiGeneraliDocumento { get; set; }

        /// <summary>
        /// Gets or Sets DatiOrdineAcquisto
        /// </summary>
        [DataMember(Name = "dati_ordine_acquisto", EmitDefaultValue = true)]
        public List<DatiOrdineAcquisto> DatiOrdineAcquisto { get; set; }

        /// <summary>
        /// Gets or Sets DatiContratto
        /// </summary>
        [DataMember(Name = "dati_contratto", EmitDefaultValue = true)]
        public List<DatiContratto> DatiContratto { get; set; }

        /// <summary>
        /// Gets or Sets DatiConvenzione
        /// </summary>
        [DataMember(Name = "dati_convenzione", EmitDefaultValue = true)]
        public List<DatiConvenzione> DatiConvenzione { get; set; }

        /// <summary>
        /// Gets or Sets DatiRicezione
        /// </summary>
        [DataMember(Name = "dati_ricezione", EmitDefaultValue = true)]
        public List<DatiRicezione> DatiRicezione { get; set; }

        /// <summary>
        /// Gets or Sets DatiFattureCollegate
        /// </summary>
        [DataMember(Name = "dati_fatture_collegate", EmitDefaultValue = true)]
        public List<DatiFattureCollegate> DatiFattureCollegate { get; set; }

        /// <summary>
        /// Gets or Sets DatiSal
        /// </summary>
        [DataMember(Name = "dati_sal", EmitDefaultValue = true)]
        public List<DatiSAL> DatiSal { get; set; }

        /// <summary>
        /// Gets or Sets DatiDdt
        /// </summary>
        [DataMember(Name = "dati_ddt", EmitDefaultValue = true)]
        public List<DatiDDT> DatiDdt { get; set; }

        /// <summary>
        /// Gets or Sets DatiTrasporto
        /// </summary>
        [DataMember(Name = "dati_trasporto", EmitDefaultValue = false)]
        public DatiTrasporto DatiTrasporto { get; set; }

        /// <summary>
        /// Gets or Sets FatturaPrincipale
        /// </summary>
        [DataMember(Name = "fattura_principale", EmitDefaultValue = false)]
        public FatturaPrincipale FatturaPrincipale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DatiGenerali {\n");
            sb.Append("  DatiGeneraliDocumento: ").Append(DatiGeneraliDocumento).Append("\n");
            sb.Append("  DatiOrdineAcquisto: ").Append(DatiOrdineAcquisto).Append("\n");
            sb.Append("  DatiContratto: ").Append(DatiContratto).Append("\n");
            sb.Append("  DatiConvenzione: ").Append(DatiConvenzione).Append("\n");
            sb.Append("  DatiRicezione: ").Append(DatiRicezione).Append("\n");
            sb.Append("  DatiFattureCollegate: ").Append(DatiFattureCollegate).Append("\n");
            sb.Append("  DatiSal: ").Append(DatiSal).Append("\n");
            sb.Append("  DatiDdt: ").Append(DatiDdt).Append("\n");
            sb.Append("  DatiTrasporto: ").Append(DatiTrasporto).Append("\n");
            sb.Append("  FatturaPrincipale: ").Append(FatturaPrincipale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
