/*
 * Italian Invoice API
 *
 *  ## Overview  The Invoice API is a RESTful API that allows you to send and receive invoices through the Italian Servizio di Interscambio (Interchange Service).  ### Authentication  The Invoicetronic API uses API keys to authenticate requests. If you don't have any API Key, you can request one by registering with the [Invoicetronic Developer Portal][1].  Test mode secret keys have the prefix `ik_test_` and live mode secret keys have the prefix `ik_live_`. Make sure to use the correct key for each environment.  > Your API keys carry many privileges, so be sure to keep them secure! Do not share your secret API keys in publicly > accessible areas such as GitHub, client-side code, and so forth.  All API requests must be made over HTTPS. Calls made over plain HTTP will fail. API requests without authentication will also fail.  #### Basic Authentication  Basic Authentication is how you authenticate with the API. Use your API Key as the username and leave the password empty. If your client does not allow empty passwords, you can use any value as the password. Here's an example of how to authenticate with Basic Authentication and curl:  ```curl curl https://api.invoicetronic.com/invoice/v1/send \\     -u ik_test_1234567890abcdefg:  # The colon prevents curl from asking for a password. ```  [1]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: v1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Anagrafica
    /// </summary>
    [DataContract(Name = "Anagrafica")]
    public partial class Anagrafica : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Anagrafica" /> class.
        /// </summary>
        /// <param name="denominazione">denominazione.</param>
        /// <param name="nome">nome.</param>
        /// <param name="cognome">cognome.</param>
        /// <param name="titolo">titolo.</param>
        /// <param name="codEori">codEori.</param>
        public Anagrafica(string denominazione = default(string), string nome = default(string), string cognome = default(string), string titolo = default(string), string codEori = default(string))
        {
            this.Denominazione = denominazione;
            this.Nome = nome;
            this.Cognome = cognome;
            this.Titolo = titolo;
            this.CodEori = codEori;
        }

        /// <summary>
        /// Gets or Sets Denominazione
        /// </summary>
        [DataMember(Name = "denominazione", EmitDefaultValue = true)]
        public string Denominazione { get; set; }

        /// <summary>
        /// Gets or Sets Nome
        /// </summary>
        [DataMember(Name = "nome", EmitDefaultValue = true)]
        public string Nome { get; set; }

        /// <summary>
        /// Gets or Sets Cognome
        /// </summary>
        [DataMember(Name = "cognome", EmitDefaultValue = true)]
        public string Cognome { get; set; }

        /// <summary>
        /// Gets or Sets Titolo
        /// </summary>
        [DataMember(Name = "titolo", EmitDefaultValue = true)]
        public string Titolo { get; set; }

        /// <summary>
        /// Gets or Sets CodEori
        /// </summary>
        [DataMember(Name = "cod_eori", EmitDefaultValue = true)]
        public string CodEori { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Anagrafica {\n");
            sb.Append("  Denominazione: ").Append(Denominazione).Append("\n");
            sb.Append("  Nome: ").Append(Nome).Append("\n");
            sb.Append("  Cognome: ").Append(Cognome).Append("\n");
            sb.Append("  Titolo: ").Append(Titolo).Append("\n");
            sb.Append("  CodEori: ").Append(CodEori).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
